defaults:
  - base

data:
  cluster_path: null
  cache_dir: ${oc.env:PROJECT_ROOT}/data/mof/cif_inf_100

diffuser:
  diffuse_rot: False

experiment:
  name: mof_translation

  # training mode
  use_ddp: False
  # Take early checkpoint at step 100. Helpful for catching eval bugs early.
  early_ckpt: True

  # Training arguments
  log_freq: 1000
  num_epoch: 4000
  batch_size: 256
  max_squared_res: 100000 # adjust this instead of batch size 
  rot_loss_t_threshold: 0.0
  rot_loss_weight: 1.0
  separate_rot_loss: False
  sample_mode: time_batch
  aux_loss_weight: null
  
  # Wandb logging
  wandb_dir: ${oc.env:WANDB_DIR}
  use_wandb: False
  project: TEST

  # How many steps to checkpoint between.
  ckpt_freq: 5000

model:
  max_radius: 10
  max_neighbors: 32
  max_atoms: 100
  time_dim: 256
  hidden_dim: 256
  act_fn: silu
  n_layers: 6